---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0

  - hooks:
      - id: black
    repo: https://github.com/ambv/black
    rev: 23.1.0

  - hooks:
      - id: prettier
        types_or: [css, javascript, markdown, scss, yaml, gitignore, toml]
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4

  - hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.0.0

  - hooks:
      - args:
          - --all
        id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1

  - hooks:
      - args:
          - -iii
          - -ll
        id: bandit
    repo: https://github.com/pycqa/bandit
    rev: 1.7.4

  - hooks:
      - id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971

  - hooks:
      - id: reorder-python-imports
    repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0

  - hooks:
      - additional_dependencies:
          - toml
        id: pydocstyle
    repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
  - hooks:
      - args:
          - --py36-plus
          - --py37-plus
          - --py38-plus
          - --py39-plus
          - --py310-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3

  - hooks:
      - id: hadolint
    repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
